# Generated by Django 5.1.7 on 2025-03-22 21:30

import Book_Inventry.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book_description', models.TextField()),
                ('book_created_at', models.DateTimeField()),
                ('book_updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Book_Inventry.models.book_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book_Inventry.books')),
            ],
        ),
    ]
