# Generated by Django 5.1.7 on 2025-03-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Inventry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
